/*|
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.tiendalibros.presentacion;

import co.unicauca.tiendalibros.modelo.*;
import static co.unicauca.tiendalibros.modelo.Catalogo.leerAlmacen;
import java.awt.Image;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class GUITiendaLibros extends javax.swing.JFrame {

    Lista<Libro> catalogo;
    
    FuncionHash funcionhash = new FuncionHash();
    
    /**
     * Creates new form GUITiendaLibros
     */
    public GUITiendaLibros() {
        catalogo = new Lista<>();
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            // TODO add your handling code here:
            leerAlmacen(catalogo, rootPane);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(GUITiendaLibros.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            mostrarLibros(catalogo, catalogo.getTamanio());
        } catch (PosicionIlegalException ex) {
            Logger.getLogger(GUITiendaLibros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editarlibro = new javax.swing.JInternalFrame();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        editarcategoria = new javax.swing.JComboBox<>();
        editaridioma = new javax.swing.JComboBox<>();
        editareditorial = new javax.swing.JTextField();
        editaranio = new javax.swing.JTextField();
        editaredicion = new javax.swing.JTextField();
        editartitulo = new javax.swing.JTextField();
        editarisbn = new javax.swing.JTextField();
        aceptareditar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        editarautores = new javax.swing.JTable();
        cerrareditar = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        editarresumen = new javax.swing.JTextPane();
        fondomostrar1 = new javax.swing.JLabel();
        MostrarLibro = new javax.swing.JInternalFrame();
        isbn = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        edicion = new javax.swing.JLabel();
        idioma = new javax.swing.JLabel();
        editar = new javax.swing.JButton();
        anio = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        autores = new javax.swing.JTable();
        editorial = new javax.swing.JLabel();
        categoria = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        cerrarMostrar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resumen = new javax.swing.JTextPane();
        fondomostrar = new javax.swing.JLabel();
        eliminarlibro = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        isbn1 = new javax.swing.JTextField();
        eliminar1 = new javax.swing.JButton();
        cancelareliminacion = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();
        buscarLibro = new javax.swing.JInternalFrame();
        jLabel12 = new javax.swing.JLabel();
        isbnbusqueda = new javax.swing.JTextField();
        buscarporisbn = new javax.swing.JButton();
        buscarrapido = new javax.swing.JButton();
        cancelarbusqueda = new javax.swing.JButton();
        fondobuscar = new javax.swing.JLabel();
        Ttitulo = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        agregarlibro = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        imagen1 = new javax.swing.JLabel();
        Libro1 = new javax.swing.JLabel();
        Libro2 = new javax.swing.JLabel();
        Libro3 = new javax.swing.JLabel();
        Libro4 = new javax.swing.JLabel();
        Libro5 = new javax.swing.JLabel();
        Libro6 = new javax.swing.JLabel();
        Libro7 = new javax.swing.JLabel();
        Libro8 = new javax.swing.JLabel();
        Libro9 = new javax.swing.JLabel();
        Libro10 = new javax.swing.JLabel();
        imagen2 = new javax.swing.JLabel();
        imagen3 = new javax.swing.JLabel();
        imagen4 = new javax.swing.JLabel();
        imagen5 = new javax.swing.JLabel();
        imagen6 = new javax.swing.JLabel();
        imagen7 = new javax.swing.JLabel();
        imagen8 = new javax.swing.JLabel();
        imagen9 = new javax.swing.JLabel();
        imagen10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editarlibro.setVisible(false);
        editarlibro.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("ISBN: ");
        editarlibro.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 70, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Titulo: ");
        editarlibro.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 70, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Autores:");
        editarlibro.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 90, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Edición: ");
        editarlibro.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 70, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Idioma: ");
        editarlibro.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 70, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Año: ");
        editarlibro.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 70, 20));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Editorial:");
        editarlibro.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 70, 20));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Resumen:");
        editarlibro.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 90, 20));

        editarcategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Programación", "sistemas operativos", "ingeniería de software", "redes", "seguridad informática", "gestión de proyectos informáticos", "otra" }));
        editarlibro.getContentPane().add(editarcategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 180, -1));

        editaridioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "Ingles" }));
        editaridioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editaridiomaActionPerformed(evt);
            }
        });
        editarlibro.getContentPane().add(editaridioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 100, -1));
        editarlibro.getContentPane().add(editareditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 220, -1));
        editarlibro.getContentPane().add(editaranio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 220, -1));
        editarlibro.getContentPane().add(editaredicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 220, -1));
        editarlibro.getContentPane().add(editartitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 220, -1));
        editarlibro.getContentPane().add(editarisbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 220, -1));

        aceptareditar.setBackground(new java.awt.Color(102, 255, 0));
        aceptareditar.setForeground(new java.awt.Color(255, 255, 255));
        aceptareditar.setText("Aceptar");
        aceptareditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptareditarActionPerformed(evt);
            }
        });
        editarlibro.getContentPane().add(aceptareditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, -1, -1));

        editarautores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido"
            }
        ));
        jScrollPane3.setViewportView(editarautores);
        if (editarautores.getColumnModel().getColumnCount() > 0) {
            editarautores.getColumnModel().getColumn(0).setResizable(false);
            editarautores.getColumnModel().getColumn(1).setResizable(false);
        }

        editarlibro.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 360, 90));

        cerrareditar.setBackground(new java.awt.Color(255, 51, 0));
        cerrareditar.setForeground(new java.awt.Color(255, 255, 255));
        cerrareditar.setText("Cancelar");
        cerrareditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrareditarActionPerformed(evt);
            }
        });
        editarlibro.getContentPane().add(cerrareditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Categoría:");
        editarlibro.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 90, 20));

        jScrollPane4.setViewportView(editarresumen);

        editarlibro.getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 360, 80));

        fondomostrar1.setBackground(new java.awt.Color(255, 255, 255));
        fondomostrar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        fondomostrar1.setOpaque(true);
        editarlibro.getContentPane().add(fondomostrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 530));

        getContentPane().add(editarlibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 430, 560));

        MostrarLibro.setVisible(false);
        MostrarLibro.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        MostrarLibro.getContentPane().add(isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 210, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("ISBN: ");
        MostrarLibro.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 70, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Titulo: ");
        MostrarLibro.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 70, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Autores:");
        MostrarLibro.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 90, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Edición: ");
        MostrarLibro.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 70, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Idioma: ");
        MostrarLibro.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 70, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Año: ");
        MostrarLibro.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 70, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Editorial:");
        MostrarLibro.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 70, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Resumen:");
        MostrarLibro.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 90, 20));
        MostrarLibro.getContentPane().add(edicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 240, 20));
        MostrarLibro.getContentPane().add(idioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 240, 20));

        editar.setBackground(new java.awt.Color(0, 0, 0));
        editar.setForeground(new java.awt.Color(255, 255, 255));
        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        MostrarLibro.getContentPane().add(editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, -1, -1));
        MostrarLibro.getContentPane().add(anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 240, 20));

        autores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(autores);
        if (autores.getColumnModel().getColumnCount() > 0) {
            autores.getColumnModel().getColumn(0).setResizable(false);
            autores.getColumnModel().getColumn(1).setResizable(false);
        }

        MostrarLibro.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 360, 90));
        MostrarLibro.getContentPane().add(editorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 240, 20));
        MostrarLibro.getContentPane().add(categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 240, 20));
        MostrarLibro.getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 240, 20));

        cerrarMostrar.setBackground(new java.awt.Color(255, 51, 0));
        cerrarMostrar.setForeground(new java.awt.Color(255, 255, 255));
        cerrarMostrar.setText("Cerrar");
        cerrarMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarMostrarActionPerformed(evt);
            }
        });
        MostrarLibro.getContentPane().add(cerrarMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Categoría:");
        MostrarLibro.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 90, 20));

        jScrollPane1.setViewportView(resumen);

        MostrarLibro.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 360, 80));

        fondomostrar.setBackground(new java.awt.Color(255, 255, 255));
        fondomostrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        fondomostrar.setOpaque(true);
        MostrarLibro.getContentPane().add(fondomostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 530));

        getContentPane().add(MostrarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 430, 560));

        eliminarlibro.setVisible(false);
        eliminarlibro.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("ISBN:");
        eliminarlibro.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 40, 20));

        isbn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbn1ActionPerformed(evt);
            }
        });
        eliminarlibro.getContentPane().add(isbn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 190, -1));

        eliminar1.setBackground(new java.awt.Color(0, 0, 0));
        eliminar1.setForeground(new java.awt.Color(255, 255, 255));
        eliminar1.setText("Eliminar Libro");
        eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar1ActionPerformed(evt);
            }
        });
        eliminarlibro.getContentPane().add(eliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 110, -1));

        cancelareliminacion.setBackground(new java.awt.Color(255, 0, 0));
        cancelareliminacion.setForeground(new java.awt.Color(255, 255, 255));
        cancelareliminacion.setText("Cancelar");
        cancelareliminacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelareliminacionActionPerformed(evt);
            }
        });
        eliminarlibro.getContentPane().add(cancelareliminacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 110, -1));

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        fondo.setOpaque(true);
        eliminarlibro.getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 140));

        getContentPane().add(eliminarlibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 370, 170));

        buscarLibro.setVisible(false);
        buscarLibro.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("ISBN:");
        buscarLibro.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 40, 20));

        isbnbusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnbusquedaActionPerformed(evt);
            }
        });
        buscarLibro.getContentPane().add(isbnbusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 190, -1));

        buscarporisbn.setBackground(new java.awt.Color(0, 255, 0));
        buscarporisbn.setForeground(new java.awt.Color(255, 255, 255));
        buscarporisbn.setText("Buscar");
        buscarporisbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarporisbnActionPerformed(evt);
            }
        });
        buscarLibro.getContentPane().add(buscarporisbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        buscarrapido.setBackground(new java.awt.Color(255, 255, 0));
        buscarrapido.setForeground(new java.awt.Color(255, 255, 255));
        buscarrapido.setText("Rapida");
        buscarrapido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarrapidoActionPerformed(evt);
            }
        });
        buscarLibro.getContentPane().add(buscarrapido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        cancelarbusqueda.setBackground(new java.awt.Color(255, 0, 0));
        cancelarbusqueda.setForeground(new java.awt.Color(255, 255, 255));
        cancelarbusqueda.setText("Cancelar");
        cancelarbusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarbusquedaActionPerformed(evt);
            }
        });
        buscarLibro.getContentPane().add(cancelarbusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 110, -1));

        fondobuscar.setBackground(new java.awt.Color(255, 255, 255));
        fondobuscar.setOpaque(true);
        buscarLibro.getContentPane().add(fondobuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 110));

        getContentPane().add(buscarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 330, 140));

        Ttitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Ttitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ttitulo.setText("CATALOGO DE LIBROS DE EDITORIAL ATLANTES");
        Ttitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(Ttitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 810, 50));

        Salir.setBackground(new java.awt.Color(0, 0, 0));
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 70, -1));

        agregarlibro.setBackground(new java.awt.Color(0, 0, 0));
        agregarlibro.setForeground(new java.awt.Color(255, 255, 255));
        agregarlibro.setText("Agregar Libro");
        agregarlibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarlibroActionPerformed(evt);
            }
        });
        getContentPane().add(agregarlibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 120, -1));

        actualizar.setBackground(new java.awt.Color(0, 0, 0));
        actualizar.setForeground(new java.awt.Color(255, 255, 255));
        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });
        getContentPane().add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        eliminar.setBackground(new java.awt.Color(0, 0, 0));
        eliminar.setForeground(new java.awt.Color(255, 255, 255));
        eliminar.setText("Eliminar Libro");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 120, -1));

        imagen1.setOpaque(true);
        imagen1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagen1MouseClicked(evt);
            }
        });
        getContentPane().add(imagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 130, 170));

        Libro1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Libro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 130, 20));

        Libro2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Libro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 130, 20));

        Libro3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Libro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 130, 20));

        Libro4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Libro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 130, 20));

        Libro5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Libro5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 130, 20));

        Libro6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Libro6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 130, 20));

        Libro7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Libro7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 130, 20));

        Libro8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Libro8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, 130, 20));

        Libro9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Libro9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 530, 130, 20));

        Libro10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Libro10, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 530, 130, 20));

        imagen2.setOpaque(true);
        imagen2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagen2MouseClicked(evt);
            }
        });
        getContentPane().add(imagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 130, 170));

        imagen3.setOpaque(true);
        imagen3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagen3MouseClicked(evt);
            }
        });
        getContentPane().add(imagen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 130, 170));

        imagen4.setOpaque(true);
        imagen4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagen4MouseClicked(evt);
            }
        });
        getContentPane().add(imagen4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 130, 170));

        imagen5.setOpaque(true);
        imagen5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagen5MouseClicked(evt);
            }
        });
        getContentPane().add(imagen5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, 130, 170));

        imagen6.setOpaque(true);
        imagen6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagen6MouseClicked(evt);
            }
        });
        getContentPane().add(imagen6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 130, 170));

        imagen7.setOpaque(true);
        imagen7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagen7MouseClicked(evt);
            }
        });
        getContentPane().add(imagen7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 130, 170));

        imagen8.setOpaque(true);
        imagen8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagen8MouseClicked(evt);
            }
        });
        getContentPane().add(imagen8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 130, 170));

        imagen9.setOpaque(true);
        imagen9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagen9MouseClicked(evt);
            }
        });
        getContentPane().add(imagen9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 130, 170));

        imagen10.setOpaque(true);
        imagen10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagen10MouseClicked(evt);
            }
        });
        getContentPane().add(imagen10, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, 130, 170));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Buscar ISBN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 90, -1));

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Fondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Fondo.setName(""); // NOI18N
        Fondo.setOpaque(true);
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 602));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void agregarlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarlibroActionPerformed
        // TODO add your handling code here:
        AgregarLibro.main();
    }//GEN-LAST:event_agregarlibroActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        dispose();
        new GUITiendaLibros().setVisible(true);
    }//GEN-LAST:event_actualizarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        eliminarlibro.setVisible(true);
    }//GEN-LAST:event_eliminarActionPerformed

    private void eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar1ActionPerformed
        try {
            Catalogo.removerLibro(isbn1.getText(), catalogo, rootPane);
        } catch (PosicionIlegalException | IOException ex) {
            Logger.getLogger(GUITiendaLibros.class.getName()).log(Level.SEVERE, null, ex);
        }
        eliminarlibro.dispose();
    }//GEN-LAST:event_eliminar1ActionPerformed

    private void isbn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbn1ActionPerformed

    private void cancelareliminacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelareliminacionActionPerformed
        eliminarlibro.dispose();
    }//GEN-LAST:event_cancelareliminacionActionPerformed

    private void imagen1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagen1MouseClicked
        // TODO add your handling code here:
        MostrarLibro.setVisible(true);
        for(int i=0; i < catalogo.getTamanio(); i++){
            try {
                if(Libro1.getText().equals(catalogo.getValor(i).getTitulo())){
                    isbn.setText(Long.toString(catalogo.getValor(i).getISBN()));
                    titulo.setText(catalogo.getValor(i).getTitulo());
                    edicion.setText(catalogo.getValor(i).getEdicion());
                    idioma.setText(catalogo.getValor(i).getIdioma());
                    anio.setText(catalogo.getValor(i).getAnio());
                    editorial.setText(catalogo.getValor(i).getEditorial());
                    categoria.setText(catalogo.getValor(i).getCategoria());
                    resumen.setText(catalogo.getValor(i).getResumen());
                    DefaultTableModel temp = (DefaultTableModel) autores.getModel();
                    for(int j=0; j < catalogo.getValor(i).getListaAutores().getTamanio();j++){
                        Object nuevo[]= {catalogo.getValor(i).getListaAutores().getValor(j).getNombre(),catalogo.getValor(i).getListaAutores().getValor(j).getApellido()};
                        temp.addRow(nuevo);
                    }
                }
            } catch (PosicionIlegalException ex) {
                Logger.getLogger(GUITiendaLibros.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_imagen1MouseClicked

    private void cerrarMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarMostrarActionPerformed
         MostrarLibro.dispose();
        DefaultTableModel temp = (DefaultTableModel) autores.getModel();
        temp.setRowCount(0);
        
    }//GEN-LAST:event_cerrarMostrarActionPerformed

    private void imagen2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagen2MouseClicked
        // TODO add your handling code here:
        MostrarLibro.setVisible(true);
        for(int i=0; i < catalogo.getTamanio(); i++){
            try {
                if(Libro2.getText().equals(catalogo.getValor(i).getTitulo())){
                    isbn.setText(Long.toString(catalogo.getValor(i).getISBN()));
                    titulo.setText(catalogo.getValor(i).getTitulo());
                    edicion.setText(catalogo.getValor(i).getEdicion());
                    idioma.setText(catalogo.getValor(i).getIdioma());
                    anio.setText(catalogo.getValor(i).getAnio());
                    editorial.setText(catalogo.getValor(i).getEditorial());
                    categoria.setText(catalogo.getValor(i).getCategoria());
                    resumen.setText(catalogo.getValor(i).getResumen());
                    DefaultTableModel temp = (DefaultTableModel) autores.getModel();
                    for(int j=0; j < catalogo.getValor(i).getListaAutores().getTamanio();j++){
                        Object nuevo[]= {catalogo.getValor(i).getListaAutores().getValor(j).getNombre(),catalogo.getValor(i).getListaAutores().getValor(j).getApellido()};
                        temp.addRow(nuevo);
                    }
                }
            } catch (PosicionIlegalException ex) {
                Logger.getLogger(GUITiendaLibros.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_imagen2MouseClicked

    private void imagen3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagen3MouseClicked
        // TODO add your handling code here:
        MostrarLibro.setVisible(true);
        for(int i=0; i < catalogo.getTamanio(); i++){
            try {
                if(Libro3.getText().equals(catalogo.getValor(i).getTitulo())){
                    isbn.setText(Long.toString(catalogo.getValor(i).getISBN()));
                    titulo.setText(catalogo.getValor(i).getTitulo());
                    edicion.setText(catalogo.getValor(i).getEdicion());
                    idioma.setText(catalogo.getValor(i).getIdioma());
                    anio.setText(catalogo.getValor(i).getAnio());
                    editorial.setText(catalogo.getValor(i).getEditorial());
                    categoria.setText(catalogo.getValor(i).getCategoria());
                    resumen.setText(catalogo.getValor(i).getResumen());
                    DefaultTableModel temp = (DefaultTableModel) autores.getModel();
                    for(int j=0; j < catalogo.getValor(i).getListaAutores().getTamanio();j++){
                        Object nuevo[]= {catalogo.getValor(i).getListaAutores().getValor(j).getNombre(),catalogo.getValor(i).getListaAutores().getValor(j).getApellido()};
                        temp.addRow(nuevo);
                    }
                }
            } catch (PosicionIlegalException ex) {
                Logger.getLogger(GUITiendaLibros.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_imagen3MouseClicked

    private void imagen4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagen4MouseClicked
        // TODO add your handling code here:
        MostrarLibro.setVisible(true);
        for(int i=0; i < catalogo.getTamanio(); i++){
            try {
                if(Libro4.getText().equals(catalogo.getValor(i).getTitulo())){
                    isbn.setText(Long.toString(catalogo.getValor(i).getISBN()));
                    titulo.setText(catalogo.getValor(i).getTitulo());
                    edicion.setText(catalogo.getValor(i).getEdicion());
                    idioma.setText(catalogo.getValor(i).getIdioma());
                    anio.setText(catalogo.getValor(i).getAnio());
                    editorial.setText(catalogo.getValor(i).getEditorial());
                    categoria.setText(catalogo.getValor(i).getCategoria());
                    resumen.setText(catalogo.getValor(i).getResumen());
                    DefaultTableModel temp = (DefaultTableModel) autores.getModel();
                    for(int j=0; j < catalogo.getValor(i).getListaAutores().getTamanio();j++){
                        Object nuevo[]= {catalogo.getValor(i).getListaAutores().getValor(j).getNombre(),catalogo.getValor(i).getListaAutores().getValor(j).getApellido()};
                        temp.addRow(nuevo);
                    }
                }
            } catch (PosicionIlegalException ex) {
                Logger.getLogger(GUITiendaLibros.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_imagen4MouseClicked

    private void imagen5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagen5MouseClicked
        // TODO add your handling code here:
        MostrarLibro.setVisible(true);
        for(int i=0; i < catalogo.getTamanio(); i++){
            try {
                if(Libro5.getText().equals(catalogo.getValor(i).getTitulo())){
                    isbn.setText(Long.toString(catalogo.getValor(i).getISBN()));
                    titulo.setText(catalogo.getValor(i).getTitulo());
                    edicion.setText(catalogo.getValor(i).getEdicion());
                    idioma.setText(catalogo.getValor(i).getIdioma());
                    anio.setText(catalogo.getValor(i).getAnio());
                    editorial.setText(catalogo.getValor(i).getEditorial());
                    categoria.setText(catalogo.getValor(i).getCategoria());
                    resumen.setText(catalogo.getValor(i).getResumen());
                    DefaultTableModel temp = (DefaultTableModel) autores.getModel();
                    for(int j=0; j < catalogo.getValor(i).getListaAutores().getTamanio();j++){
                        Object nuevo[]= {catalogo.getValor(i).getListaAutores().getValor(j).getNombre(),catalogo.getValor(i).getListaAutores().getValor(j).getApellido()};
                        temp.addRow(nuevo);
                    }
                }
            } catch (PosicionIlegalException ex) {
                Logger.getLogger(GUITiendaLibros.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_imagen5MouseClicked

    private void imagen6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagen6MouseClicked
        // TODO add your handling code here:
        MostrarLibro.setVisible(true);
        for(int i=0; i < catalogo.getTamanio(); i++){
            try {
                if(Libro6.getText().equals(catalogo.getValor(i).getTitulo())){
                    isbn.setText(Long.toString(catalogo.getValor(i).getISBN()));
                    titulo.setText(catalogo.getValor(i).getTitulo());
                    edicion.setText(catalogo.getValor(i).getEdicion());
                    idioma.setText(catalogo.getValor(i).getIdioma());
                    anio.setText(catalogo.getValor(i).getAnio());
                    editorial.setText(catalogo.getValor(i).getEditorial());
                    categoria.setText(catalogo.getValor(i).getCategoria());
                    resumen.setText(catalogo.getValor(i).getResumen());
                    DefaultTableModel temp = (DefaultTableModel) autores.getModel();
                    for(int j=0; j < catalogo.getValor(i).getListaAutores().getTamanio();j++){
                        Object nuevo[]= {catalogo.getValor(i).getListaAutores().getValor(j).getNombre(),catalogo.getValor(i).getListaAutores().getValor(j).getApellido()};
                        temp.addRow(nuevo);
                    }
                }
            } catch (PosicionIlegalException ex) {
                Logger.getLogger(GUITiendaLibros.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_imagen6MouseClicked

    private void imagen7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagen7MouseClicked
        // TODO add your handling code here:
        MostrarLibro.setVisible(true);
        for(int i=0; i < catalogo.getTamanio(); i++){
            try {
                if(Libro7.getText().equals(catalogo.getValor(i).getTitulo())){
                    isbn.setText(Long.toString(catalogo.getValor(i).getISBN()));
                    titulo.setText(catalogo.getValor(i).getTitulo());
                    edicion.setText(catalogo.getValor(i).getEdicion());
                    idioma.setText(catalogo.getValor(i).getIdioma());
                    anio.setText(catalogo.getValor(i).getAnio());
                    editorial.setText(catalogo.getValor(i).getEditorial());
                    categoria.setText(catalogo.getValor(i).getCategoria());
                    resumen.setText(catalogo.getValor(i).getResumen());
                    DefaultTableModel temp = (DefaultTableModel) autores.getModel();
                    for(int j=0; j < catalogo.getValor(i).getListaAutores().getTamanio();j++){
                        Object nuevo[]= {catalogo.getValor(i).getListaAutores().getValor(j).getNombre(),catalogo.getValor(i).getListaAutores().getValor(j).getApellido()};
                        temp.addRow(nuevo);
                    }
                }
            } catch (PosicionIlegalException ex) {
                Logger.getLogger(GUITiendaLibros.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_imagen7MouseClicked

    private void imagen8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagen8MouseClicked
        // TODO add your handling code here:
        MostrarLibro.setVisible(true);
        for(int i=0; i < catalogo.getTamanio(); i++){
            try {
                if(Libro8.getText().equals(catalogo.getValor(i).getTitulo())){
                    isbn.setText(Long.toString(catalogo.getValor(i).getISBN()));
                    titulo.setText(catalogo.getValor(i).getTitulo());
                    edicion.setText(catalogo.getValor(i).getEdicion());
                    idioma.setText(catalogo.getValor(i).getIdioma());
                    anio.setText(catalogo.getValor(i).getAnio());
                    editorial.setText(catalogo.getValor(i).getEditorial());
                    categoria.setText(catalogo.getValor(i).getCategoria());
                    resumen.setText(catalogo.getValor(i).getResumen());
                    DefaultTableModel temp = (DefaultTableModel) autores.getModel();
                    for(int j=0; j < catalogo.getValor(i).getListaAutores().getTamanio();j++){
                        Object nuevo[]= {catalogo.getValor(i).getListaAutores().getValor(j).getNombre(),catalogo.getValor(i).getListaAutores().getValor(j).getApellido()};
                        temp.addRow(nuevo);
                    }
                }
            } catch (PosicionIlegalException ex) {
                Logger.getLogger(GUITiendaLibros.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_imagen8MouseClicked

    private void imagen9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagen9MouseClicked
        // TODO add your handling code here:
        MostrarLibro.setVisible(true);
        for(int i=0; i < catalogo.getTamanio(); i++){
            try {
                if(Libro9.getText().equals(catalogo.getValor(i).getTitulo())){
                    isbn.setText(Long.toString(catalogo.getValor(i).getISBN()));
                    titulo.setText(catalogo.getValor(i).getTitulo());
                    edicion.setText(catalogo.getValor(i).getEdicion());
                    idioma.setText(catalogo.getValor(i).getIdioma());
                    anio.setText(catalogo.getValor(i).getAnio());
                    editorial.setText(catalogo.getValor(i).getEditorial());
                    categoria.setText(catalogo.getValor(i).getCategoria());
                    resumen.setText(catalogo.getValor(i).getResumen());
                    DefaultTableModel temp = (DefaultTableModel) autores.getModel();
                    for(int j=0; j < catalogo.getValor(i).getListaAutores().getTamanio();j++){
                        Object nuevo[]= {catalogo.getValor(i).getListaAutores().getValor(j).getNombre(),catalogo.getValor(i).getListaAutores().getValor(j).getApellido()};
                        temp.addRow(nuevo);
                    }
                }
            } catch (PosicionIlegalException ex) {
                Logger.getLogger(GUITiendaLibros.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_imagen9MouseClicked

    private void imagen10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagen10MouseClicked
        // TODO add your handling code here:
        MostrarLibro.setVisible(true);
        for(int i=0; i < catalogo.getTamanio(); i++){
            try {
                if(Libro10.getText().equals(catalogo.getValor(i).getTitulo())){
                    isbn.setText(Long.toString(catalogo.getValor(i).getISBN()));
                    titulo.setText(catalogo.getValor(i).getTitulo());
                    edicion.setText(catalogo.getValor(i).getEdicion());
                    idioma.setText(catalogo.getValor(i).getIdioma());
                    anio.setText(catalogo.getValor(i).getAnio());
                    editorial.setText(catalogo.getValor(i).getEditorial());
                    categoria.setText(catalogo.getValor(i).getCategoria());
                    resumen.setText(catalogo.getValor(i).getResumen());
                    DefaultTableModel temp = (DefaultTableModel) autores.getModel();
                    for(int j=0; j < catalogo.getValor(i).getListaAutores().getTamanio();j++){
                        Object nuevo[]= {catalogo.getValor(i).getListaAutores().getValor(j).getNombre(),catalogo.getValor(i).getListaAutores().getValor(j).getApellido()};
                        temp.addRow(nuevo);
                    }
                }
            } catch (PosicionIlegalException ex) {
                Logger.getLogger(GUITiendaLibros.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_imagen10MouseClicked

    private void isbnbusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbnbusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbnbusquedaActionPerformed

    private void cancelarbusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarbusquedaActionPerformed
        buscarLibro.dispose();
    }//GEN-LAST:event_cancelarbusquedaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        buscarLibro.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buscarporisbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarporisbnActionPerformed
        Libro libro = new Libro();
        try {
            libro = Catalogo.buscarISBN(Long.parseLong(isbnbusqueda.getText()), catalogo, rootPane);
                if(isbnbusqueda.getText().equals(Long.toString(libro.getISBN()))){
                    MostrarLibro.setVisible(true);
                    isbn.setText(Long.toString(libro.getISBN()));
                    titulo.setText(libro.getTitulo());
                    edicion.setText(libro.getEdicion());
                    idioma.setText(libro.getIdioma());
                    anio.setText(libro.getAnio());
                    editorial.setText(libro.getEditorial());
                    categoria.setText(libro.getCategoria());
                    resumen.setText(libro.getResumen());
                    DefaultTableModel temp = (DefaultTableModel) autores.getModel();
                    for(int j=0; j < libro.getListaAutores().getTamanio();j++){
                        Object nuevo[]= {libro.getListaAutores().getValor(j).getNombre(),libro.getListaAutores().getValor(j).getApellido()};
                        temp.addRow(nuevo);
                    }
                    isbnbusqueda.setText("");
                    buscarLibro.dispose();
                }
        } catch (PosicionIlegalException ex) {
            Logger.getLogger(GUITiendaLibros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buscarporisbnActionPerformed

    private void cerrareditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrareditarActionPerformed
        editarlibro.dispose();
    }//GEN-LAST:event_cerrareditarActionPerformed

    private void editaridiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editaridiomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editaridiomaActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        editarlibro.setVisible(true);
        MostrarLibro.dispose();
        editarisbn.setText(isbn.getText());
        editartitulo.setText(titulo.getText());
        editaredicion.setText(edicion.getText());
        editaranio.setText(anio.getText());
        editareditorial.setText(editorial.getText());
        editarresumen.setText(resumen.getText());
        DefaultTableModel temp = (DefaultTableModel) editarautores.getModel();
        for(int j=0; j < autores.getRowCount();j++){
            Object nuevo[]= {autores.getValueAt(j, 0),autores.getValueAt(j, 1)};
            temp.addRow(nuevo);
        }
    }//GEN-LAST:event_editarActionPerformed

    private void aceptareditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptareditarActionPerformed
        Libro libro = new Libro();
        Lista<Autor> autoreseditar = new Lista<>();
        for(int i=0; i < catalogo.getTamanio();i++){
            try {
                if(catalogo.getValor(i).getTitulo().equals(titulo.getText())){
                    libro.setISBN(Long.parseLong(editarisbn.getText()));
                    libro.setTitulo(editartitulo.getText());
                    libro.setEdicion(editaredicion.getText());
                    libro.setIdioma(editaridioma.getSelectedItem().toString());
                    libro.setAnio(editaranio.getText());
                    libro.setEditorial(editareditorial.getText());
                    libro.setCategoria(editarcategoria.getSelectedItem().toString());
                    libro.setResumen(editarresumen.getText());
                    libro.setCaratuladellibro(catalogo.getValor(i).getCaratuladellibro());
                    for(int j=0;j<editarautores.getRowCount();j++){
                        Autor autor = new Autor();
                        autor.setNombre(editarautores.getValueAt(j, 0).toString());
                        autor.setApellido(editarautores.getValueAt(j, 1).toString());
                        autoreseditar.agregar(autor);
                    }
                    libro.setListaAutores(autoreseditar);
                    catalogo.remover(i);
                    catalogo.insertar(libro, catalogo.getTamanio());
                    Catalogo.guardarLibros(catalogo);
                    editarlibro.dispose();
                }
            } catch (PosicionIlegalException ex) {
                Logger.getLogger(GUITiendaLibros.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(GUITiendaLibros.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_aceptareditarActionPerformed

    private void buscarrapidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarrapidoActionPerformed
        try {
            Libro librohash = funcionhash.funcionhash(((int) (Double.parseDouble(this.isbnbusqueda.getText())%100)), catalogo);
            if (librohash == null) {
                JOptionPane.showMessageDialog(this, "El libro no se encuentra en la lista.", "Buscar libro", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "El libro ha sido encontrado con éxito.", "Buscar libro", JOptionPane.INFORMATION_MESSAGE);
            }
            buscarLibro.dispose();
        } catch (PosicionIlegalException ex) {
            Logger.getLogger(GUITiendaLibros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buscarrapidoActionPerformed

    private void mostrarLibros(Lista<Libro> Libros, int tamanio) throws PosicionIlegalException {
        int contador = 0;
        if (contador < tamanio) {
            Libro1.setText(Libros.getValor(0).getTitulo());
            ImageIcon ImgIcon = new ImageIcon(Consola.decodificarImagen(catalogo.getValor(0).getCaratuladellibro()));
            Icon imagen = new ImageIcon(ImgIcon.getImage().getScaledInstance(imagen1.getWidth(), imagen1.getHeight(), Image.SCALE_DEFAULT));
            imagen1.setIcon(imagen);
            contador++;
        }
        if (contador < tamanio) {
            Libro2.setText(Libros.getValor(1).getTitulo());
            ImageIcon ImgIcon = new ImageIcon(Consola.decodificarImagen(catalogo.getValor(1).getCaratuladellibro()));
            Icon imagen = new ImageIcon(ImgIcon.getImage().getScaledInstance(imagen2.getWidth(), imagen2.getHeight(), Image.SCALE_DEFAULT));
            imagen2.setIcon(imagen);
            contador++;
        }
        if (contador < tamanio) {
            Libro3.setText(Libros.getValor(2).getTitulo());
            ImageIcon ImgIcon = new ImageIcon(Consola.decodificarImagen(catalogo.getValor(2).getCaratuladellibro()));
            Icon imagen = new ImageIcon(ImgIcon.getImage().getScaledInstance(imagen3.getWidth(), imagen3.getHeight(), Image.SCALE_DEFAULT));
            imagen3.setIcon(imagen);
            contador++;
        }
        if (contador < tamanio) {
            Libro4.setText(Libros.getValor(3).getTitulo());
            ImageIcon ImgIcon = new ImageIcon(Consola.decodificarImagen(catalogo.getValor(3).getCaratuladellibro()));
            Icon imagen = new ImageIcon(ImgIcon.getImage().getScaledInstance(imagen4.getWidth(), imagen4.getHeight(), Image.SCALE_DEFAULT));
            imagen4.setIcon(imagen);
            contador++;
        }
        if (contador < tamanio) {
            Libro5.setText(Libros.getValor(4).getTitulo());
            ImageIcon ImgIcon = new ImageIcon(Consola.decodificarImagen(catalogo.getValor(4).getCaratuladellibro()));
            Icon imagen = new ImageIcon(ImgIcon.getImage().getScaledInstance(imagen5.getWidth(), imagen5.getHeight(), Image.SCALE_DEFAULT));
            imagen5.setIcon(imagen);
            contador++;
        }
        if (contador < tamanio) {
            Libro6.setText(Libros.getValor(5).getTitulo());
            ImageIcon ImgIcon = new ImageIcon(Consola.decodificarImagen(catalogo.getValor(5).getCaratuladellibro()));
            Icon imagen = new ImageIcon(ImgIcon.getImage().getScaledInstance(imagen6.getWidth(), imagen6.getHeight(), Image.SCALE_DEFAULT));
            imagen6.setIcon(imagen);
            contador++;
        }
        if (contador < tamanio) {
            Libro7.setText(Libros.getValor(6).getTitulo());
            ImageIcon ImgIcon = new ImageIcon(Consola.decodificarImagen(catalogo.getValor(6).getCaratuladellibro()));
            Icon imagen = new ImageIcon(ImgIcon.getImage().getScaledInstance(imagen7.getWidth(), imagen7.getHeight(), Image.SCALE_DEFAULT));
            imagen7.setIcon(imagen);
            contador++;
        }
        if (contador < tamanio) {
            Libro8.setText(Libros.getValor(7).getTitulo());
            ImageIcon ImgIcon = new ImageIcon(Consola.decodificarImagen(catalogo.getValor(7).getCaratuladellibro()));
            Icon imagen = new ImageIcon(ImgIcon.getImage().getScaledInstance(imagen8.getWidth(), imagen8.getHeight(), Image.SCALE_DEFAULT));
            imagen8.setIcon(imagen);
            contador++;
        }
        if (contador < tamanio) {
            Libro9.setText(Libros.getValor(8).getTitulo());
            ImageIcon ImgIcon = new ImageIcon(Consola.decodificarImagen(catalogo.getValor(8).getCaratuladellibro()));
            Icon imagen = new ImageIcon(ImgIcon.getImage().getScaledInstance(imagen9.getWidth(), imagen9.getHeight(), Image.SCALE_DEFAULT));
            imagen9.setIcon(imagen);
            contador++;
        }
        if (contador < tamanio) {
            Libro10.setText(Libros.getValor(9).getTitulo());
            ImageIcon ImgIcon = new ImageIcon(Consola.decodificarImagen(catalogo.getValor(9).getCaratuladellibro()));
            Icon imagen = new ImageIcon(ImgIcon.getImage().getScaledInstance(imagen10.getWidth(), imagen10.getHeight(), Image.SCALE_DEFAULT));
            imagen10.setIcon(imagen);
            contador++;
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUITiendaLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUITiendaLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUITiendaLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUITiendaLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUITiendaLibros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Libro1;
    private javax.swing.JLabel Libro10;
    private javax.swing.JLabel Libro2;
    private javax.swing.JLabel Libro3;
    private javax.swing.JLabel Libro4;
    private javax.swing.JLabel Libro5;
    private javax.swing.JLabel Libro6;
    private javax.swing.JLabel Libro7;
    private javax.swing.JLabel Libro8;
    private javax.swing.JLabel Libro9;
    private javax.swing.JInternalFrame MostrarLibro;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel Ttitulo;
    private javax.swing.JButton aceptareditar;
    private javax.swing.JButton actualizar;
    private javax.swing.JButton agregarlibro;
    private javax.swing.JLabel anio;
    private javax.swing.JTable autores;
    private javax.swing.JInternalFrame buscarLibro;
    private javax.swing.JButton buscarporisbn;
    private javax.swing.JButton buscarrapido;
    private javax.swing.JButton cancelarbusqueda;
    private javax.swing.JButton cancelareliminacion;
    private javax.swing.JLabel categoria;
    private javax.swing.JButton cerrarMostrar;
    private javax.swing.JButton cerrareditar;
    private javax.swing.JLabel edicion;
    private javax.swing.JButton editar;
    private javax.swing.JTextField editaranio;
    private javax.swing.JTable editarautores;
    private javax.swing.JComboBox<String> editarcategoria;
    private javax.swing.JTextField editaredicion;
    private javax.swing.JTextField editareditorial;
    private javax.swing.JComboBox<String> editaridioma;
    private javax.swing.JTextField editarisbn;
    private javax.swing.JInternalFrame editarlibro;
    private javax.swing.JTextPane editarresumen;
    private javax.swing.JTextField editartitulo;
    private javax.swing.JLabel editorial;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton eliminar1;
    private javax.swing.JInternalFrame eliminarlibro;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondobuscar;
    private javax.swing.JLabel fondomostrar;
    private javax.swing.JLabel fondomostrar1;
    private javax.swing.JLabel idioma;
    private javax.swing.JLabel imagen1;
    private javax.swing.JLabel imagen10;
    private javax.swing.JLabel imagen2;
    private javax.swing.JLabel imagen3;
    private javax.swing.JLabel imagen4;
    private javax.swing.JLabel imagen5;
    private javax.swing.JLabel imagen6;
    private javax.swing.JLabel imagen7;
    private javax.swing.JLabel imagen8;
    private javax.swing.JLabel imagen9;
    private javax.swing.JLabel isbn;
    private static javax.swing.JTextField isbn1;
    private static javax.swing.JTextField isbnbusqueda;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane resumen;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
